metrics:
  enabled: true
container:
  pool:
    cpus: 2
    memory: 1024
api:
  port: 1323
  ip: 10.10.1.2
cloud:
  server:
    url: http://10.10.2.2:1325
scheduler:
  policy: edgeonly
  #policy: edgeCluster
  cloud:
    cost: 0.0001
registry:
  udp:
    port: 9876
etcd:
  address: 10.10.2.2:2379