metrics:
  enabled: true
container:
  pool:
    cpus: 4
    memory: 20480
api:
  port: 1325
  ip: 10.10.2.2
scheduler:
  policy: edgeonly
  cloud:
    cost: 0.0001
registry:
  udp:
    port: 9876
  #area: MILAN
etcd:
  address: 10.10.2.2:2379